name: reviewdog
on: 
  pull_request:
    branches: 
      - main
jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.token }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup node/npm
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: textlint-github-check
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.token }}
          reporter: github-check
          level: warning
          textlint_flags: "*.md markdown/*jp.md"
      - name: textlint-github-pr-check
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.token }}
          reporter: github-pr-check
          level: warning
          textlint_flags: "*.md markdown/*jp.md"
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.token }}
          reporter: github-pr-review
          level: warning
          textlint_flags: "*.md markdown/*jp.md"
